languageCode = 'en-us'
title = 'Richbase Solutions'
theme = "ananke"

# Set the Base URL to match your GitHub Pages structure
baseURL = "https://dxzweb.github.io/richbase/"

# Set the publishing directory to 'docs'
publishDir = "docs"